### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by 15991361037** [fh2019ustc/DocTr#25]
Traceback (most recent call last):
  File "E:\jiaozheng\DocTr-main\inference.py", line 138, in <module>
    main()
  File "E:\jiaozheng\DocTr-main\inference.py", line 134, in main
    rec(opt)
  File "E:\jiaozheng\DocTr-main\inference.py", line 76, in rec
    GeoTr_Seg_model = GeoTr_Seg().cuda()
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "E:\jiaozheng\DocTr-main\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Tarek-Eladly** [comment]
Open the project in any code editor => replace all in all the files cuda with cpu ... performance will drop

**Comment by fh2019ustc** [comment]
@Tarek-Eladly Ah... I am also confused.

**Comment by Tarek-Eladly** [comment]
Some devices/setups don't support GPU(CUDA), so switching to CPU to make it work ... you need to configure/setup your system to support GPU(CUDA) so it works correctly

**Comment by Tarek-Eladly** [comment]
@fh2019ustc Thank you for this wonderful Doc preparation tool for OCR really thanks

**Comment by fh2019ustc** [comment]
@Tarek-Eladly Glad it's helpful for you! Feel free to let me know if you encounter any other issues. 😊
